#!/bin/sh

PHPCS_BIN="/your/path/phpcs"
PHPCS_CODING_STANDARD="PSR2"

TMP_DIR=$(mktemp -d phpcs-pre-receive-hook.XXXXXXXX)
mkdir "$TMP_DIR/source"

ERRORS="PSR2 Verified"
RETVAL=0

while read oldrev newrev refname
do
    if [ "$oldrev" = "0000000000000000000000000000000000000000" ]
    then
        oldrev="HEAD"
    fi

    list=$(git diff-tree --name-only -r $oldrev..$newrev | grep -e '.php$')
    for file in ${list}; do

        mkdir -p $(dirname "$TMP_DIR/source/$file")

        git show ${newrev}:${file} 1>"$TMP_DIR/source/$file" 2>/dev/null  || continue  #skip deleted files
        OUTPUT=$($PHPCS_BIN  --standard=$PHPCS_CODING_STANDARD "$TMP_DIR/source/$file")
        if [ "$?" -ne "0" ]; then
            ERRORS="${ERRORS}${OUTPUT}"
            RETVAL=1
        fi

    done
done

rm -rf $TMP_DIR

echo "$ERRORS"
exit $RETVAL